version: "3.9"
services:
  db:
    image: postgres:16
    container_name: tents_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tents
    ports:
      - "5432:5432"   # si 5432 est√° ocupado en tu host, cambialo a "5433:5432"
    volumes:
      - db_data_tents:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tents"]
      interval: 5s
      timeout: 3s
      retries: 10
volumes:
  db_data_tents: